POST http://localhost:8000/api/matches
content-type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2ODE4NDI4OTcsImV4cCI6MTY4MTkwNzY5Nywicm9sZXMiOlsiUk9MRV9VU0VSIl0sInVzZXJuYW1lIjoiZmFyZmFkZXRAc2VsbGVyLmNvbSJ9.XV8Vo5Twk3TGLXR3GVH9tnJSAWHuxzBL_VWot49LPwgThqezbHsWERu0P2SBYL-IqE9FaA-MKGbpEC0UOrUV8ZgJuzB2jnzBOr6QOwDIafkT3qqQjkFxQ52DqdZrqMuchfIwyQnivHoGM7oMokiw3PqF0LxIYCfQfHBirUhfaOMwaEBMYR-HOZIVQY1XUzFdYAFEPodfdeGoSOcyqQo8Jtzjn4BVvYuoVeizWyMPUlTE4OVA8xLJBEw8uUqhoXknjRpDlE0ap7zszXbZPnFoKP5-CmgjDd1fayyfkX0lPq_sXl_riYHYURidqglDuKgdslAIlLgIIyvletUXvyeg4A

{
    "receiver": 2,
    "isMutual":true
}