GET http://localhost:8000/api/users/matches/mutual
content-type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2ODE2ODQ4NjUsImV4cCI6MTY4MTc0OTY2NSwicm9sZXMiOlsiUk9MRV9VU0VSIl0sInVzZXJuYW1lIjoieW91bmVzQHNlbGxlci5jb20ifQ.Ls12Pf6YCyWoTlypTQix9kHv7lD-pFd8mx0uzK0VFqfKGWsTCDXFbSREaak79Rkv53qkpa1uaFQR6i5IOGS3U4cKRilCK2wy11piqIBreFsYYkUNjuCBXKrYpGphVstDfPppEhfLhtgZRPW0MSRcfh6t1tGVLbUaUobaCiTdJj90D2JI0IFZYGHzmqespBn3Tnh0bgV1uDC5hDs68EaUEfWslopIW4Nu1J2novLFG1rb4X3vDbDrgA_7jfeF7tySx488E42i5F4a6nVr3wjOfKldFbmj2HO4O99vf_WO0SZEx0tbMXlrPmo3wW7Cde3-p8dl8zOWHl1jB6zl7t1D1Q
