PUT http://localhost:8000/api/matches/10
content-type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2ODE4NDMzODYsImV4cCI6MTY4MTkwODE4Niwicm9sZXMiOlsiUk9MRV9VU0VSIl0sInVzZXJuYW1lIjoiYm91eWFrYUBzZWxsZXIuY29tIn0.h3CZwWce5VE3SM5uU_cxQ91t0udoPwG4ycq7HdxZFoMMZ98d7sT4MRiyNiAj7UDQEIfWfL_JQdFA5FXvDDaGqiP_gvpB04MZOTJjpy3zeoNfCSM5U_v5qB5d743qsyleSN2N7SM5b2Bhtg3bSQSwDtFy0wNwoxQl8EwF_zEx70KLb9QJT_SXrp2sz-R61T36Mq5H8no8fcU4_yfvAtITlHcfg4kzRd0QrXP1XKgdCbl4pXnMSjtR8Nvyq3KZiHvz_2e-YSt6NYSORWq-qNuONOUe63kZD5TO5drQl9Ji_QY1rKvVYyKKNyE9XTmrfyJ9zPzkm1-yaqZxktkRomoWeA
