DELETE http://localhost:8000/api/matches/11
content-type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2ODIxNzkxMzcsImV4cCI6MTY4MjI0MzkzNywicm9sZXMiOlsiUk9MRV9VU0VSIl0sInVzZXJuYW1lIjoiY2Fycm91ZkBzZWxsZXIuY29tIn0.P3CbrnIIjS1GL92eshSCqbbFBMBZPvJm3PgGdrJHylniMog-HhLcE0gff9U-kBKyCQmuZ4gHl_kWYhgugpV0MiZ2HCDQkTIk9DMElhlko2N_1WTDT6BoB5blZV2zDrnez3NPSNEP09-_mUdUTrt6Vz0MJjoaElIWwPHobf_nsvzcApuuX-OcaZLDTZhGW2ccEZtPLBJ30GrXitLOvx31GyUn5DvB3XQbTggvVOaD5nre7UKUcPJB7HgdqiuickLHw1rau51Wz1YyHLw-jwMkOBuLdn6CfqqYftrSQ55odpKHmsG0A96k7sMXyQnzjNqyOam2Qa24W2bFuEEpLvSJmg