GET http://localhost:8000/api/users/matches/from
content-type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2ODIyNjg0MzIsImV4cCI6MTY4MjMzMzIzMiwicm9sZXMiOlsiUk9MRV9BRE1JTiIsIlJPTEVfVVNFUiJdLCJ1c2VybmFtZSI6ImFkbWluQHNlbGxlci5jb20ifQ.r8iFXjctRWuV8NKlyo4yzOGMsPKeGuxr3wu7ALXQP9z8FwG1OZM6Ghw-_CvfFlklj7A2oErsTycXRvPk6cmsGysoUO_HhusPhPRXS6t_5wjd8maKgOQOdqwFHsHQA78p8tOLOsZpO_pjhUPf10W1ALwnI2tNCyPFLWAxvuo7CbeAo6AYrOc_1hs3kebjK63SrHBi1T9IP2LBlLhCwjW32kWs1dhCKlGE25bPp8pvzRwwhmofkKG1JJhaSzQN2VDJMUmroKbO4olaM7BuK00p2O5PNeChRG8ln87VJ1xJRmtKR2F-Mo2L33Ll_cyLWILqh5pRSu-QSVdovTt_ThKQVw
