POST http://localhost:8000/api/users/15/skill
content-type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2ODE2ODY3OTMsImV4cCI6MTY4MTc1MTU5Mywicm9sZXMiOlsiUk9MRV9VU0VSIl0sInVzZXJuYW1lIjoieW91bmVzQHNlbGxlci5jb20ifQ.WDB5oDSH-Cg7vbzMEBgJrWomY46NPeguNk0PzrXVXHNX3ioilnPRT6syCy8L3rFynkj956cSSyWFkQWXbgBX1754dHjCqbEu8tcDMrEDHEdcQoa_ffotlY8eic9v0f75NsblVr0vyLbDTN09EiivseZp4GiZu4pfrpMlTRaftI6Yc8vB-FT1q403gZr3jAVIiYP6oh9kYvddrxS87a_UZciqWKRC215eExgXIJnMVDn7z5KE98D_3sp-Y5c-1NICAxqjshrxjCCmIUYPK5P8Ib2Jm4MzUaW_hadkjr3k-Lr3UCyJPkngVY8GNhT7ajD0IIotBW6cMJ1PCl9u8O7V8g

{
  "skillList": [2]
}
