DELETE http://localhost:8000/api/users/15/skill
content-type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2ODE2ODgzNTEsImV4cCI6MTY4MTc1MzE1MSwicm9sZXMiOlsiUk9MRV9VU0VSIl0sInVzZXJuYW1lIjoieW91bmVzQHNlbGxlci5jb20ifQ.oX7Cxmkvw1FOzsgWv34QdqH2wdsty2FLsH5mYtlGvWMPDdA4WEhJUKjE7zdk-4G7510Qm46mAMCuqJ__bEOfJYUAN6OXsbBzk4YV98Bog37m-EGNVFTPRDcM89HUUvq0wBwRYFifBCjYRb97jYPSxJOzqTVXQvuk6MeIUBuFsJMGJM2SiusbBHTfXDVIz6I-EbAhMpdUf3sBNczxrM8otPdJjmDU5XjCiO9SfU8lwvnWUCN9DbrwEF4nQspRfBKCT1BZuO6v0FAFRAGEXpoycHMeZIsBMNBdZltG5e4v5RF5gTrmNTrbn6UfLdl-iFM6fmFhiUQIcv8oYASF7obQXg

{
  "skillList": [25]
}
