GET http://localhost:8000/api/skills
content-type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2ODE2ODc2NzMsImV4cCI6MTY4MTc1MjQ3Mywicm9sZXMiOlsiUk9MRV9VU0VSIl0sInVzZXJuYW1lIjoieW91bmVzQHNlbGxlci5jb20ifQ.U_2f6kBWdWxl27NOdjZzFrw9BDQcnfAJ9vxja0iU2cywIt_pLJQivvbKR2SY25MHv4uUixZSLKHoqrtMuXYPCS0v6-9Msxe7RVVaEGZcvixqDKHPBtYtSLsF9FC06OT1PrYloBbwVEAXt8u1fHsUBSVPNiRnLCxzvdBWK5iBfavlHL_GPksvrxBKypUbRamKONjHVyxpuas1VdNuaWgG31t9PFaQ31-ChCTssFLgUE-KlFSwhDjd6tIVRd--JWT19-ngzTPqhZSmKMi4qxwfWNXZ0cr4pzXMxy--zlanByHJnV9Zp_G4TnNdI8M6T7C57aKao32ckAmbeV-li1BSiw

