GET http://localhost:8000/api/users/15
content-type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2ODE2ODM3MzcsImV4cCI6MTY4MTc0ODUzNywicm9sZXMiOlsiUk9MRV9VU0VSIl0sInVzZXJuYW1lIjoieW91bmVzQHNlbGxlci5jb20ifQ.1roDfGnrxgI7GKZwYn9YE2ny7Rnsb9QHk6svx5FlzF9yM-J1jbfu74G3M7aekTzKAj0J-qv4XU7_2sYmeIha9GCWiT_i39yffloMjBCiqKp22tcH5ettZBJWaCoxsGJ-0o5QeZL7r4D3dn_xBnLjLLjifhajW68G9NEg1cG9kbeq4RK_Lbj4_mdI9PPSCQ5g0sz_6VOlzbWIcfdb5u7WXU-h6ECzMmIyucwDQtpyvhHdT6PAjq2GSCRQbaXCGwtGhrqp_aPTqjaV1VC-L6RoT-w6kpX_3h_qUjiURJpFiHJ_JlzWMuewdg9kEG7_tVgf4ql920mb5UELpXSlDYenM

