GET http://localhost:8000/api/users/type/STUDENT
content-type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2ODE2NzUzNDYsImV4cCI6MTY4MTc0MDE0Niwicm9sZXMiOlsiUk9MRV9VU0VSIl0sInVzZXJuYW1lIjoieW91bmVzQHNlbGxlci5jb20ifQ.2kok1KAFAvL_YV4WSUE3H43uyuphXk1w-eMufOC9rT6aPXlr3mLh7BK2tknDKmDo9zOxwGfnalglP1Kzy6aOFVSDqAO_zMdb_mus190AaoW2ULav6ecZEO0GUddAY8Qw-bO-Q2ZgGQuB5vQkiaHAJColCBqkxnv0cETgKn7RZf8vA-g8ME9ZZQrfqE3jBUICa05yIErs7avg7QJsUAQnCMlgoOnGBPP1bo808tkTUsCtrl1Qt4l3_QQzH2u5AjCquwGiUT6MAqIuCA3wXebKkWg6hTvl5I2_gLm1lVyLJL2mW0Z1oAqqoYqbKpXVUilNgL0ZC3K9M2CJnIINOglYSw
