PUT http://localhost:8000/api/users/16
content-type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2ODE2ODM5NDIsImV4cCI6MTY4MTc0ODc0Miwicm9sZXMiOlsiUk9MRV9VU0VSIl0sInVzZXJuYW1lIjoieW91bmVzQHNlbGxlci5jb20ifQ.mT7HrCybrVvvJ3AJCoqOnW5_ZC8K541xoxqB-Czl4bWZJUgvRlBc0GE0m3M-xQhSLlrY5LU8CLshXtHU_2d9DcwHACAMTGNo5IsoDZovzPWjMmdxHhORPnJM0N2hRZ-vgVY_tC9eT-WlgoZrZA_u5lIay2thkIpi13RXaHg65nPW66orwBGqNAdqa6kskTE3Jnb9laKjwfNpEzYvHBZVRs8kTt_4u9r5t3x9RrTlCkuludabIsWhfbMsr2kHnLzj38sOn3YkwSldIh-6-lAxncIkYLL2H2dCKB2sknZhCy1qV4J8C8Y4Y7-90RhAGpMfKr0VMksxSvyRyQisUV57j

{
    "company_name": "toto"
}