<?php

namespace ContainerTOaKUUc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Ems1YC4Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ems1YC4' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ems1YC4'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'skillRepository' => ['privates', 'App\\Repository\\SkillRepository', 'getSkillRepositoryService', true],
        ], [
            'skillRepository' => 'App\\Repository\\SkillRepository',
        ]);
    }
}
