<?php

namespace ContainerTOaKUUc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GwPNHVwService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.GwPNHVw' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.GwPNHVw'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'emailSender' => ['privates', 'App\\Service\\EmailSenderService', 'getEmailSenderServiceService', true],
        ], [
            'emailSender' => 'App\\Service\\EmailSenderService',
        ]);
    }
}
