<?php

namespace ContainerTOaKUUc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KdRCMpGService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.KdRCMpG' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.KdRCMpG'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'user' => ['privates', '.errored..service_locator.KdRCMpG.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.KdRCMpG": it references class "App\\Entity\\User" but no such service exists.'],
            'userPasswordHasherInterface' => ['privates', 'security.user_password_hasher', 'getSecurity_UserPasswordHasherService', true],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'user' => 'App\\Entity\\User',
            'userPasswordHasherInterface' => '?',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
