<?php

namespace ContainerTOaKUUc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_1zxlVgkService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.1zxlVgk' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.1zxlVgk'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'myMatchRepository' => ['privates', 'App\\Repository\\MyMatchRepository', 'getMyMatchRepositoryService', true],
        ], [
            'myMatchRepository' => 'App\\Repository\\MyMatchRepository',
        ]);
    }
}
