<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTOaKUUc\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTOaKUUc/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTOaKUUc.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTOaKUUc\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTOaKUUc\App_KernelDevDebugContainer([
    'container.build_hash' => 'TOaKUUc',
    'container.build_id' => '8aa9a38f',
    'container.build_time' => 1685439127,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTOaKUUc');
